[tool.poetry]
name = "OpenCLAI"
version = "0.1.0"
description = ""
authors = ["Paul Hutchins <paul.hutchins@uptickhq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
